# Конфигурация для Telegram бота

# Настройки бота (без токена - он в secrets-tgbot.yaml)
bot:
  username: "@SSAU_SoftDevMgmt_bot"
  # token загружается из secrets-tgbot.yaml

# Настройки функциональности бота
features:
  enable_reviews: true  # Включить/выключить функцию оценивания участников
  max_sprint_number: 6  # Максимальный номер спринта
  min_rating: 1  # Минимальная оценка
  max_rating: 10  # Максимальная оценка

# Логирование специфичное для бота
logging:
  file: logs/studhelper-bot.log
