# Конфигурация для веб-приложения

# Настройки веб-сервера
web:
  host: 127.0.0.1
  port: 8000
  reload: true  # Автоперезагрузка при изменениях (только для разработки)

# Логирование специфичное для веба
logging:
  file: logs/studteams-web.log
